#!/usr/bin/env python3
# -*- coding: utf-8 -*-


from dataclasses import dataclass, field
from typing import List


@dataclass
class KickstartConfig:
    # --- Étape 1 : Identité & Localisation ---
    distribution: str = ""
    langue: str = "fr_FR.UTF-8"
    timezone: str = "Europe/Paris"
    clavier: str = "fr-oss_latin9"

    # --- Étape 2 : Utilisateurs (Nouveau) ---
    root_pw_crypted: str = ""  # On stocke le hash directement
    user_name: str = "Toto"
    user_gecos: str = "Toto"
    user_pw_crypted: str = ""
    user_groups: str = "wheel"

    # --- Étape 3 : Partitionnement Manuel (Nouveau) ---
    # On peut stocker les lignes de partitionnement sous forme de liste
    partitions: List[str] = field(default_factory=lambda: [
        'part /boot --fstype="ext4" --ondisk=sda --size=1024 --label=boot',
        'part /boot/efi --fstype="efi" --ondisk=sda --size=500 --fsoptions="umask=0077,shortname=winnt" --label=efi',
        'part / --fstype="ext4" --ondisk=sda --size=61440 --label=root',
        'part swap --fstype="swap" --ondisk=sda --size=4096'
    ])
    ignoredisk: str = "sda"

    # --- Étape 4 : Paquets ---
    # Notez l'utilisation du préfixe @ pour les groupes d'environnement
    packages: List[str] = field(default_factory=lambda: [
        "@^xfce-desktop-environment",
        "@development-tools",
        "vlc"
    ])

    # --- Étape 5 : Système & Auth ---
    authselect: str = "enable-feature with-fingerprint"
    firstboot: bool = True

    def generate_ks(self) -> str:
        # Gestion du clavier spécifique Fedora
        vckeymap = self.clavier
        if "-" in vckeymap:
            layout, variant = vckeymap.split("-", 1)
            xlayout = f"{layout} ({variant})"
        else:
            xlayout = vckeymap

        lines = [
            "# Generated by Anacontux",
            f"keyboard --vckeymap={vckeymap} --xlayouts='{xlayout}'",
            f"lang {self.langue}",
            "",
            "%packages"
        ]

        # Ajout des paquets
        lines.extend(self.packages)
        lines.append("%end")
        lines.append("")

        # Système
        lines.append(f"authselect {self.authselect}")
        lines.append(f"firstboot {'--enable' if self.firstboot else '--disable'}")
        lines.append("")

        # Partitionnement
        lines.append(f"ignoredisk --only-use={self.ignoredisk}")
        lines.append("clearpart --none --initlabel")
        lines.extend(self.partitions)
        lines.append("")

        # Timezone & Users
        lines.append(f"timezone {self.timezone} --utc")
        lines.append(f"rootpw --iscrypted {self.root_pw_crypted}")
        lines.append(
            f"user --groups={self.user_groups} --name={self.user_name} --password={self.user_pw_crypted} --iscrypted --gecos=\"{self.user_gecos}\"")

        return "\n".join(lines)